# Generated by Django 3.2.7 on 2024-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0002_sahlaboost'),
    ]

    operations = [
        migrations.CreateModel(
            name='activation_money_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=310, null=True)),
                ('conferm_serial', models.CharField(blank=True, max_length=310, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('Prenom', models.CharField(blank=True, max_length=120, null=True)),
                ('num_phone', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
