# Generated by Django 3.2.7 on 2024-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0003_activation_money_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel_video', models.CharField(blank=True, max_length=500, null=True)),
                ('url_video', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
