# Generated by Django 3.2.7 on 2024-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0005_link_chromedriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweettype',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='domainname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sweettype',
            name='wilaya',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
