# Generated by Django 3.2.7 on 2025-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0006_auto_20241206_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_chromedriver',
            name='desktop_file_path',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='link_chromedriver',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
