# Generated by Django 3.2.7 on 2025-01-17 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sweet_shared', '0007_auto_20250110_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('numbercemande', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='عدد الطلبيات')),
                ('package', models.CharField(blank=True, choices=[('free', 'الباقة المجانية'), ('advanced', 'الباقة المتطورة'), ('legendary', 'الباقة الأسطورية')], max_length=50, null=True, verbose_name='الباقة')),
                ('payment_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع الدفع')),
                ('upload_receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='رفع الوصل')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
