# Generated by Django 3.2.7 on 2025-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0008_add_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_payments',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد مراجعة'), ('active', 'نشطة'), ('completed', 'مكتملة'), ('rejected', 'رفض')], max_length=50, null=True, verbose_name='الحالة'),
        ),
    ]
