# Generated by Django 3.2.7 on 2025-01-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0010_alter_add_payments_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_payments',
            name='user',
        ),
    ]
