# Generated by Django 3.2.7 on 2025-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0011_remove_add_payments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='orderpri',
            new_name='advanced_package',
        ),
        migrations.AddField(
            model_name='price',
            name='legendary_package',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='order_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
