# Generated by Django 3.2.7 on 2024-06-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste_des_commandes',
            name='status',
        ),
    ]
