# Generated by Django 3.2.7 on 2025-03-14 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240802_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste_des_commandes',
            name='date_commande',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='liste_des_commandes',
            name='statut_commande',
            field=models.CharField(choices=[('new', 'جديد'), ('pending', 'قيد التأكيد'), ('call_1', 'الاتصال مرة'), ('call_2', 'الاتصال مرتين'), ('call_3', 'الاتصال ثلاث مرات'), ('confirmed', 'مؤكدة'), ('delivery', 'شركة التوصيل'), ('completed', 'مكتملة'), ('all', 'الكل')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='liste_des_commandes',
            name='url_image',
            field=models.CharField(default='https://example.com/default-image.jpg', max_length=510),
        ),
    ]
