# Generated by Django 3.2.7 on 2025-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20250314_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste_des_commandes',
            name='statut_commande',
            field=models.CharField(choices=[('new', 'جديد'), ('pending', 'قيد التأكيد'), ('call_1', 'الاتصال مرة'), ('call_2', 'الاتصال مرتين'), ('call_3', 'الاتصال ثلاث مرات'), ('confirmed', 'مؤكدة'), ('delivery', 'شركة التوصيل'), ('completed', 'مكتملة'), ('all', 'الكل')], default='new', max_length=20),
        ),
    ]
